### ISSUE TITLE
Install fails to install bash completion on OSX

### ISSUE THREAD

**Issue by jamestomasino** [jamestomasino/burrow#9]
PKG_CONFIG environment variables don't exist in the same way as on Linux. Investigate and fix.

**Comment by jamestomasino** [comment]
Makefile trying multiple locations for bash completion. It prefers `/etc/bash_completion.d/` and will attempt to use `pkgsrc` to find a location if that is not available. I need another fallback still, and then a graceful way to skip bash completion all together if a location fails to be found.

**Comment by jamestomasino** [comment]
makefile falls back nicely between several choices, including brew. If none are found, bash-completion is skipped.

**Comment by Munchotaur** [comment]
Sadly this isn't falling back well on FreeBSD. Happy to help test.

**Comment by jamestomasino** [comment]
Does it fail to run or is the failure in the install? The paths don't line up on openbsd so I imagine freebsd is similar. I'd love help improving the makefile to be better across platforms.

**Comment by Munchotaur** [comment]
It seems to be two things: one, `$PREFIX` isn't evaluating to anything using FreeBSD's native make, so the makefile looks for `/etc/bash-completion.d` rather than `/usr/local/etc/bash-completion.d`. Would testing the OS in the makefile help with this?

However from my scant reading it looks like FreeBSD's own make is quite different to GNU's. So installing `devel/gmake` and `whateveritis/bash-completion` from ports or running `sudo pkg install gmake bash-completion` then using `sudo install gmake` within the burrow folder works perfectly.

Please see #33 where I posted the steps to a working install. TBH if it's just a slight variation in install procedure, is it worth changing the makefile when a couple of lines added to the readme would suffice? We could probably look for directly equivalent steps for OpenBSD/NetBSD too.
